version: '3.8'

services:
#  db:
#    image: postgres
#    container_name: postgres_db
#    volumes:
#      - ./db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=games_sales_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./backend
#    volumes:
#      - ./backend:/games_sales_project/backend
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
#    depends_on:
#      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/games_sales_project/frontend/build
    stdin_open: true

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend/
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
