# Generated by Django 4.0.4 on 2022-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
